### PR TITLE
Display Multiday Events Correctly

### PR DESCRIPTION
**Pull request by steets250**
We haven't had many (if at all) multi-day events before, but for something like the census, I want to make it clear why it shows as upcoming for a few days.

### CODE REVIEW

**Review by StormFireFox1 — APPROVED** [review]
This was something that was kinda weird for a while, so I'm glad it's in!

I'll approve, but I'd rather we test with an event in the backend first for width in card (i.e. if the text overflows or something)

**Comment by StormFireFox1** [comment]
Pic of component overflow
Turns out the date overflows on multi-day events, we either need to:
- Make month shorter
- Remove time from date if event is spanning multiple days.

Ask Membership multi-day events are dependent on time.

**Comment by steets250** [comment]
https://github.com/acmucsd/membership-portal/issues/287

**Comment by steets250** [comment]
https://github.com/acmucsd/membership-portal/pull/294

**Comment by steets250** [comment]
Backend PR has now been merged, once the testing API has been updated this PR should be ready to verify and merge.

**Comment by steets250** [comment]
@StormFireFox1 Updated backend data is up, this PR is ready for a review.

**Review by StormFireFox1 — APPROVED** [review]
Looks absolutely perfect!

**Pull request merged**
