### PR TITLE
Update Admin Menu Checks

### PR DESCRIPTION
**Pull request by steets250**
Merch store managers and distributors didn't have access to the admin nav item for store.

### CODE REVIEW

**Comment by steets250** [comment]
I need to fix the permissions for events team, so I'll hold off on requesting review until then.

**Comment by steets250** [comment]
I'll merge from master once https://github.com/acmucsd/membership-portal-ui/pull/539 is in and make sure the route checks are correct as well.

**Comment by StormFireFox1** [comment]
@steets250 we can probably merge from master to get this back on the roll.

**Comment by StormFireFox1** [comment]
@steets250 Did you check the routes on this one? If not, lemme know so I can try it out or I can approve this.

**Review by StormFireFox1 — APPROVED** [review]
Never mind, I looked over the route checks myself.

Looks like store managers can do everything store-related, but not admin stuff, and store distributors can only prep and fulfill orders. As intended!

Well done!

**Pull request merged**
